/*
 * Flag.h
 *
 *  Created on: Jul 9, 2024
 *      Author: autives
 */

#ifndef TYPES_FLAG_H_
#define TYPES_FLAG_H_

#include <cstdint>

enum Flag : uint8_t {
  RETAIN = 0,
  QOS = 1,
  DUP = 3,
};

enum ConnectFlag : uint8_t {
  CLEAN_START = 1,
  WILL_FLAG = 2,
  WILL_QOS = 3,
  WILL_RETAIN = 5,
  PASSWORD_FLAG = 6,
  USERNAME_FLAG = 7
};

enum ConnAckFlag : uint8_t {
  SESSION_PRESENT = 0
};

enum class ReasonCode : uint8_t {

};

enum class ConnectReasonCode : uint8_t {
  SUCCESS = 0,
  UNSPECIFIED_ERROR = 128,
  MALFORMED_PACKET = 129,
  PROTOCOL_ERROR = 130,
  IMPLEMENTATION_SPECIFIC_ERROR = 131,
  UNSUPPORTED_PROTOCOL_VERSION = 132,
  CLIENT_ID_INVALID = 133,
  BAD_USER_OR_PASSWD = 134,
  NOT_AUTHORIZED = 135,
  SERVER_UNAVILABLE = 136,
  SERVER_BUSY = 137,
  BANNED = 138,
  BAD_AUTH_METHOD = 140,
  TOPIC_NAME_INVALID = 144,
  PACKET_TOO_LARGE = 149,
  QUOTA_EXCEEDED = 151,
  PAYLOAD_FORMAT_INVALID = 153,
  RETAIN_NOT_SUPPORTED = 154,
  QOS_NOT_SUPPORTED = 155,
  USE_ANOTHER_SERVER = 156,
  SERVER_MOVED = 157,
  CONN_RATE_EXCEEDED = 159
};

enum class PubAckReasonCode : uint8_t {
  SUCCESS = 0,
  NO_SUBCRIBERS = 16,
  UNSPECIFIED_ERROR = 128,
  IMPLEMENTATION_SPECIFIC_ERROR = 131,
  NOT_AUTHORIZED = 135,
  TOPIC_NAME_INVALID = 144,
  PACKET_ID_IN_USE = 145,
  QUOTA_EXCEEDED = 151,
  PAYLOAD_FORMAT_INVALID = 153
};

enum class PubRecReasonCode : uint8_t {
  
};

enum class PubRelReasonCode : uint8_t {
  SUCCESS = 0,
  PACKET_ID_NOT_FOUND = 146
};

enum class PubCompReasonCode : uint8_t {
  
};

enum class SubscribeReasonCode : uint8_t {
  GRANTED_QOS0 = 0,
  GRANTED_QOS1 = 1,
  GRANTED_QOS2 = 2,
  UNSPECIFIED_ERROR = 128,
  IMPLEMENTATION_SPECIFIC_ERROR = 131,
  NOT_AUTHORIZED = 135,
  TOPIC_FILTER_INVALID = 143,
  PACKET_ID_IN_USE = 145,
  QUOTA_EXCEEDED = 151,
  SHARED_SUBS_UNSUPPORTED = 158,
  SUB_ID_NOT_SUPPORTED = 161,
  WILDCARD_SUBS_UNSUPPORTED = 162
};

enum class UnsubscribeReasonCode : uint8_t {
  SUCCESS = 0,
  NO_SUB_EXISTED = 17,
  UNSPECIFIED_ERROR = 128,
  IMPLEMENTATION_SPECIFIC_ERROR = 131,
  NOT_AUTHORIZED = 135,
  TOPIC_FILTER_INVALID = 143,
  PACKET_ID_IN_USE = 145
};

enum class DisconnectReasonCode : uint8_t {
  NORMAL_DISCONNECTION = 0,
  DISCONNECT_WITH_WILL = 4,
  UNSPECIFIED_ERROR = 128,
  MALFORMED_PACKET = 129,
  PROTOCOL_ERROR = 130,
  IMPLEMENTATION_SPECIFIC_ERROR = 131,
  NOT_AUTHORIZED = 135,
  SERVER_BUSY = 137,
  SERVER_SHUTTING_DOWN = 139,
  KEEP_ALIVE_TIMEOUT = 141,
  SESSION_TAKEOVER = 142,
  TOPIC_FILTER_INVALID = 143,
  TOPIC_NAME_INVALID = 144,
  RECV_MAXIMUM_EXCEEDED = 147,
  TOPIC_ALIAS_INVALID = 148,
  PACKET_TOO_LARGE = 149,
  MSG_RATE_TOO_HIGH = 150,
  QUOTA_EXCEEDED = 151,
  ADMINISTRATIVE_ACTION = 152,
  PAYLOAD_FORMAT_INVALID = 153,
  RETAIN_NOT_SUPPORTED = 154,
  QOS_NOT_SUPPORTED = 155,
  USE_ANOTHER_SERVER = 156,
  SERVER_MOVED = 157,
  SHARED_SUBS_UNSUPPORTED = 158,
  CONN_RATE_EXCEEDED = 159,
  MAX_CONNECT_TIME = 160,
  SUB_ID_NOT_SUPPORTED = 161,
  WILDCARD_SUBS_NOT_SUPPORTED = 162
};

enum class AuthReasonCode : uint8_t {
  SUCCESS = 0,
  CONTINUE_AUTH = 24,
  REAUTHENTICATE = 25
};

enum class SubOpts : uint8_t {
  QOS_ZERO = 0,
  QOS_ONE = 1,
  QOS_TWO = 2,
  NO_LOCAL = 4,
  RETAIN_AS_PUBLISHED = 8,
  RETAIN_HANDLING = 16
};

#endif /* TYPES_FLAG_H_ */
